saucelabs/sauce-cypress-runner

- .eslintrc
- .github/workflows/validate.yml
- jest.config.json
- package-lock.json
- package.json
- src/custom-reporter.js
- src/cypress-runner.js
- src/sauce-reporter.js
- src/utils.js
- tests/fixtures/basic/cypress/integration/example.test.js
- tests/fixtures/config/cypress/integration/config.test.js
- tests/fixtures/env/cypress/integration/env.spec.js
- tests/unit/src/utils.spec.js
Additions:
* ESLint
* Adds the eslint-config-appium rules
* Includes fixes so that the code complies with these rules
* Jest
* Added Jest for unit testing
* Added one test that tests utils.js
* Husky
* Precommit hook that runs lint
* Pre-push hook that runs lint and tests
* GitHub Actions: validate.yml
* Runs the linter and test on every push to a PR branch or master branch
> chore: add JS linter, unit tests

- .eslintrc
- config-local.yaml
- package-lock.json
- package.json
- src/custom-reporter.js
- src/cypress-runner.js
- src/reporter-config.json
- src/sauce-reporter.js
- tests/unit/src/custom-reporter.spec.js
- tests/unit/src/sauce-reporter.spec.js
This PR has a few changes, there were a few bugs that are related to each other that need to be patched simultaneously to make asset uploading work
:bug: Bugfixes
* The custom-reporter wasn't working correctly when the spec was nested. If the spec was in something like `cypress/integration/path/to/some.spec.js` the JUnit xml and json would be moved to `cypress/reports/some.spec.js.xml|json` and the asset uploader wouldn't find it.
* Fix: Add the `specFolder` as a parameter to the reporter. The reporter then looks at the spec folder (e.g.: `cypress/integration`) and the spec file (e.g.: `cypress/integration/path/to/some.spec.js`) and infers that the relative path is `path/to/some.spec.js` and the report should be in `cypress/reports/path/to/some.spec.js.json|xml`
* Bug in `sauce-reporter` …
> fix: fixed multiple reporter bugs

- .dockerignore
- .github/workflows/helpers/print-release-id.js
- .github/workflows/release.yml
- .gitignore
- .saucetpl/.sauce/config.yml
- .saucetpl/cypress/integration/example.test.js
This PR adds (during release process) the generation of a **[saucectl](https://github.com/saucelabs/saucectl)** template to be used when initiating a new project.
It will add, to each release, a `saucetpl.tar.gz` that will contains:
- Default configuration for this runner
- An example file
Elements can be added simply by adding files/contents into the `.saucetpl` folder.
It also make `.github/workflows/helpers/print-release-id.js` repo agnostic and with no dependencies required.
> enhancements: Package a template project 

- .github/workflows/release.yml
The update of the scripts extracting the release_id required the GH_REPO to be set on.
Currently it is not, and prevent the windows artifact to be produced.
> fix: Inject repo reference while building windows artifact

- src/cypress-recorder.js
- src/sauce-reporter.js
- tests/unit/src/sauce-reporter.spec.js
When starting a bunch of tests, `cypress` clear the `reportsDir` folder and so our clone of console that we are currently recording.
To avoid that, store the recording, one folder up prevents the assets exporter from failing.
> fix: Save initial console.log not in reportsDir

- README.md
- src/cypress-runner.js
- tests/unit/src/cypress-runner.spec.js
* This PR adds a variable called `SAUCE_BROWSER_PATH` that, when set, tells Cypress to run on that path
* This, along with `BROWSER_NAME`, gets passed to Cypress.run in the form `browser="C:/path/to/browser.exe:chrome"`
Other:
* Added some more tests to further solidify cypress-runner
* Moved `BROWSER_NAME` and `BUILD_NAME` variables to the inside of functions so that they can be unit tested
> add SAUCE_BROWSER_PATH option

- package-lock.json
- package.json
- src/cypress-runner.js
- src/sauce-reporter.js
- tests/unit/src/cypress-runner.spec.js
- tests/unit/src/sauce-reporter.spec.js
Before this change: Multiple Jobs are created (one Job per spec file)
After this change: Single Job is created (regardless of the number of spec files)
Individual reports are still created for each spec file and so are the videos. However, all videos are also merged into a single large one.
In this iteration (first out of two), the image still uses `run.yaml` to be told what to run, but will work on as many test file as are listed. In the second iteration (not this PR), we'll instead pass the native test matching parameter from saucectl to the image. This could be still done via `run.yaml` if so desired or perhaps simply via env vars.
> Create one job that covers all specs

- src/cypress-recorder.js
Restore expected `exitCode` to be non-zero when some tests are failing.
Relates: https://github.com/saucelabs/testrunner-toolkit/issues/63
It's not optimum since `stream.Writable` is not cleanly closed before file being closed. As soon as operations are maid on stream either `ws.end()` or waiting for `stream.finished()`, `exitCode` resets to 0 and npm is not failing as expected.
> fix: Ensure cypress exitCode is propagated up to saucectl

- src/sauce-reporter.js
When using Electron or Firefox, the videos are consistently the same size.
When using Chrome however, the first video tends to be a different size than all the other specs.
This behavior is irrespective of what image is being used and is replicable with cypress' own docker image as well.
So for the time being, if we detect that videos are of inconsistent size, we skip the video merge.
> Don't merge videos of different sizes

- package-lock.json
- src/cypress-runner.js
- src/sauce-reporter.js
- tests/unit/src/cypress-runner.spec.js
- tests/unit/src/sauce-reporter.spec.js
* If a runner is running from inside of a Sauce VM, we don't need to create a job and upload the assets. This PR skips that step if it's a sauce VM
* Needed to do some refactoring though, because we still need the part of the recording code that prepares the assets
> skip asset upload if sauce vm

- package-lock.json
- package.json
- src/cypress-runner.js
- src/sauce-reporter.js
- tests/unit/src/__snapshots__/sauce-reporter.spec.js.snap
- tests/unit/src/sauce-reporter.spec.js
Create test result job via global data store. Currently the new approach is existed along with the previous one and will be enabled by env var `ENABLE_DATA_STORE`.
Currently even with workable creating job part, the legacy uploading part cannot co-operate with it.
> Integrate with global data store to create job

- .github/workflows/kitchen-sink.yml
- tests/kitchen-sink-tests/.sauce/config.yml
Related: https://github.com/saucelabs/sauce-cypress-runner/pull/65#discussion_r534333004
> KitchenSink - Avoid ambigous execution in case of build failure

- src/cypress-runner.js
- tests/unit/src/cypress-runner.spec.js
* Moved `prepareAssets` to after the point where we check for SAUCE_VM or sauce credentials (SAUCE_USERNAME/SAUCE_ACCESS_KEY)
* Removed the message `Skipping asset upload inside of sauce vm. Asset uploads will take place in post process batch job` because that's confusing to users who are viewing their jobs from inside a VM. Users don't have a concept of "post process batch job" and the message "Skipping asset upload" implies that something went wrong
* Moved the check for SAUCE_VM early in the method so that these logs don't show up in our VM's
```
Failed to prepare asset. Could not find: 'c:\chef\code\__project__\cypress-basic-test\__assets__\example.test.js.mp4'
Skipping asset uploads! Remember to setup your
```
> fix: re-arrange logging ot be more clear

- src/cypress-runner.js
It should display following instead of trying to create job when no credentials set
```
Skipping asset uploads! Remember to setup your SAUCE_USERNAME/SAUCE_ACCESS_KEY
```
> Do not create job when there is no credentials

- .github/workflows/release.yml
As we are moving forward, we would to align cypress runner version with cypress version.
This PR slightly modify the pipeline to ensure we are creating a release matching the defined version of Cypress.
Successful pipeline: https://github.com/FriggaHel/sauce-cypress-runner/actions/runs/499145675
Failing pipeline: https://github.com/FriggaHel/sauce-cypress-runner/runs/1736707125?check_suite_focus=true
> Implement cypress-sync'd version

- .github/workflows/release.yml
- verify_tag.sh
Support framework version as substring inside tags.
Thus a tag like `v5.6.0+v0.1.0` ought to be possible now.
> Support framework version as substring inside tags

- .github/workflows/release.yml
Removing the version enforcement, since we aren't going to include the framework version as part of the release tags anymore.
> Removing the version enforcement

- Dockerfile
- src/sauce-reporter.js
In docker mode, store job detail URL in a file to allow saucectl to retrieve it.
> Docker: Store job details url in file

- .github/workflows/release.yml
- tests/kitchen-sink-tests/.sauce/config.yml
post-release-windows-tests job runs after publish-release so when it looks for the release tag_name, don't filter by drafts.
> Don't filter by draft releases for post-release tests

- .github/workflows/kitchen-sink.yml
- .github/workflows/test.yml
Use github action `saucectl-run-action` to  run tests instead of installing manually `saucectl`.
> Use action to run tests

- .github/workflows/release.yml
- .github/workflows/test.yml
- Check for existing tag/release associated with current pipeline
- Avoid rebuilding templates/bundles
- Generate error if already publish
> CI: support restarting pipeline with no side-effects

- .github/workflows/release.yml
Post to slack if post-release job fails.
Realized the message should make it more clear which runner has failed, so message format is different from https://github.com/saucelabs/sauce-testcafe-runner/pull/72
I'll update the message from testcafe-runner to make things consistent.
> Slack failed post release

- src/custom-reporter.js
If it failed to load to the website, it would log the error like this: https://app.saucelabs.com/tests/972d3eb61ec14b02ab853f29238dfaa0
If it failed to assert some values, it would log the error like this: https://app.saucelabs.com/tests/d184faeb3b79480699be1d68deb5c558
> Add more details for failed cases

- package-lock.json
- package.json
0.4.4 has a fix for how `npm install` behaves if there is a `package-lock.json` in the cwd.
> Bump testrunner-utils

- src/sauce-reporter.js
- tests/unit/src/__snapshots__/sauce-reporter.spec.js.snap
Don't rename assets on upload. Proved to be not really necessary and visually even harder to comprehend.
> [DEVX-1136] Don't rename assets on upload

- src/cypress-runner.js
Move `headless` as part of `suite` instead of `suite.config`.
`suite.config` left for compatibility.
> [DEVX-1465] Move headless configuration to one level above

- src/cypress-runner.js
- tests/unit/src/cypress-runner.spec.js
Most of plugins relies on `process.env` as Cypress does not provides access to its internal env vars.
This MR registers env vars to the system before invoking Cypress to make them available to the plugins (or any other usages).
Also adds some changes to the tests.
Example run on Docker: https://app.saucelabs.com/tests/c294435558234f6195bd2ee376a841cf
> [DEVX-1532] Inject env vars to process.env before invoking Cypress

- src/sauce-reporter.js
If there were an error, it'd be handled like this
```
failed to generate junit file: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at Object.SauceReporter.mergeJunitFile (/home/seluser/src/sauce-reporter.js:332:37)
at SauceReporter.prepareAssets (/home/seluser/src/sauce-reporter.js:136:17)
at report (/home/seluser/src/cypress-runner.js:24:22)
at cypressRunner (/home/seluser/src/cypress-runner.js:206:16)
Using /home/seluser/__project__/__assets__/examples/1.spec.js.mp4 as the main video.
Open job details page: https://app.saucelabs.com/tests/1a01da1c215448b0bb18b1844ca34ada
suite="Chrome using global mode setting"
Results:
Name                                Duration    Status    Browser                 Platform    Attempts …
```
> [DEVX-1626] improve error handling for generating junit file

- src/cypress-runner.js
Notice this warning msg for cypress 10
```
The following configuration option is invalid:
- testingType
```
It's because of unnecessary config copy for `cypress.run()` and the result is like
```
cypressOpts:  {
testingType: 'e2e',
config: {
specPattern: [ 'cypress/e2e/**/*.js' ],
excludeSpecPattern: [],
...
testingType: 'e2e'
}
}
```
cypress throws warning for the nested `testingType` under `config`
> Remove unnecessary config copy

- package-lock.json
- package.json
* @badeball/cypress-cucumber-preprocessor
* @cypress/webpack-preprocessor
* @babel/core (peer dep)
* @babel/preset-env (peer)
* babel-loader (peer)
* webpack (peer)
* @shelex/cypress-allure-plugin
* @testing-library/cypress
* cypress-file-upload
* cypress-xpath
* cypress-wait-until
* dotenv
* cypress-mochawesome-reporter
* lodash
* typescript
These packages are not being used by the runner. Maybe they were explicit transitive dependencies? But, afaict, they aren't needed.
* glob
* js-yaml
* npm
* smart-buffer
* ts-node (@tianfeng92 this was added in your cypress 10 PR. But I don't see it used anywhere in the runner).
I did not include the older cucumber preprocessor because it does not have cypress 10 support. I'm including the allure plugin, but I wasn't able to get it to work with …
> Add packages of interest to customers

- .github/workflows/test.yml
- package-lock.json
- vendor/get-port/index.d.ts
- vendor/get-port/index.js
- vendor/get-port/license
- vendor/get-port/package.json
- vendor/get-port/readme.md
Override cypress' `get-port` library with our own.
The `get-port` lib had to be modified manually due to it being packaged as a `module`, which cypress does not support (at least not the way that Cypress is prepackaged).
The following changes were applied to `get-port`:
- remove type `module` from package.json
- replace `import` statements with `require`
- replace `export` modifiers with `module.exports`
For reference, this is why we're overriding the supplied `get-port` library:
https://github.com/cypress-io/cypress/issues/22997
Because Cypress isn't actually installed completely by NPM. Only the CLI wrapper is. The install script then downloads a prepackaged Cypress binary, which is the main part of the application that contains the `get-port` dependency.
> Override get-port library

- .github/helpers/generate-release-notes.sh
The "dependencies" object is actually obsolete, but remains for backwards compatibility. Read the cypress version from the "packages" object.
> Update parsing of cypress version from package-lock

- src/cypress-runner.ts
Only run the runner's multi reporter configuration if user has opted in via their saucectl config. This allows the user to simply configure their preferred reporting setup in their cypress config file.
[DEVX-2914]
[DEVX-2914]: https://saucedev.atlassian.net/browse/DEVX-2914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Opt in only for multi reporter configuration

- .github/workflows/test.yml
- package-lock.json
- package.json
- src/cypress-runner.ts
- src/types.ts
- tests/integration/config-tests/sauce-runner.json
- tests/integration/env-tests/sauce-runner.json
Allow the runner to determine the proper node context: bundled vs. globally installed.
The context affects how we interact with `npm`.
> feat: enable use of global node context

- .github/workflows/release.yml
Consecutive pre-releases are not currently possible. Running two release pipelines with the same pre release flavor would result in the following releases: `1.0.1-rc.0` and `1.0.2-rc.0`. But what we want when we run the second pre-release pipeline is `1.0.1-rc.1`.
Now, parse the latest release name and if the latest is a pre-release and its flavor matches the inputted flavor, we only increment the pre-release version as opposed to a full version bump.
[DEVX-3004]
[DEVX-3004]: https://saucedev.atlassian.net/browse/DEVX-3004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: Support consecutive pre releases

- .github/workflows/release.yml
- .github/workflows/test.yml
With the fix https://github.com/saucelabs/saucectl/pull/955, we can unpin saucectl version.
> ci: unpin saucectl version
