src/sauce-reporter.js

When a video is bigger than 5mb, we silently fail and on the UI we just don't show the video. Adding error messages for debugging purposes.

log upload errors

---

src/cypress-runner.js

Restrict typescript compilation to the presence of a tsconfig

---

package-lock.json
package.json
src/cypress-runner.js
src/reporter-config.json

Uses cypress-multi-reporter to report tests to both "spec" and "src/reporter.js" instead of just "src/reporter.js".
It's helpful to be able to see the test results in the standard output so that I don't have to wait until the results get uploaded before being able to see them
<details><summary>Example with "spec"</summary>
<p>
```bash
➜  sauce-cypress-runner git:(devx-269-multi-reporters) ✗ ~/saucectl/saucectl run
> sauce-cypress-runner@0.0.0 test /home/seluser
> ./bin/cypress
It looks like this is your first time using Cypress: 4.9.0
[18:36:17]  Verifying Cypress can run /home/seluser/.cache/Cypress/4.9.0/Cypress [started]
[18:36:19]  Verified Cypress!       /home/seluser/.cache/Cypress/4.9.0/Cypress [title changed]
[18:36:19]  Verified Cypress! …
```

feat: Add multi reporters

---

bin/cypress
src/cypress-recorder.js
src/sauce-reporter.js
tests/unit/src/sauce-reporter.spec.js

This PR add the console output as an asset.
It is then accessible from SauceLabs console and can be displayed.
https://app.saucelabs.com/tests/b1ea542720cd4a0cb2d29557bd0c20a4

feat: Export console output to SauceLabs

---

src/sauce-reporter.js
tests/unit/src/sauce-reporter.spec.js

Log error when there is uploading failure.

devx-333 log error when meeting uploading assets failure

---

src/cypress-recorder.js
src/cypress-runner.js
tests/kitchen-sink-tests/cypress/integration/examples/network_requests.spec.js

Install dependencies requested by user before running `cypress.run()`.

Install npm dependencies before running cypress

---

tests/kitchen-sink-tests/.sauce/config.yml
tests/kitchen-sink-tests/.sauce/config_failing_suites.yml
tests/kitchen-sink-tests/cypress/integration/failing/failing.spec.js

Write a failing test for cypress

Write a failing test for cypress

---

src/cypress-runner.js
src/sauce-reporter.js
tests/unit/src/__snapshots__/cypress-runner.spec.js.snap
tests/unit/src/__snapshots__/sauce-reporter.spec.js.snap
tests/unit/src/cypress-runner.spec.js
tests/unit/src/sauce-reporter.spec.js

This reverts commit 0e0ebb78335c084c2bc5f5d1404336b80792eea3. The upstream API is not ready net. I'll create another pull request to checking the related functions.

Revert "add function to call creating job API from test-composer (#69)"

---

.gitignore
src/cypress-runner.js
src/utils.js
tests/env-tests/.sauce/config.yml
tests/env-tests/cypress/integration/env.spec.js
tests/env-tests/sauce-runner.json
tests/integration/integration-tests.sh
tests/kitchen-sink-tests/.sauce/config.yml
tests/kitchen-sink-tests/sauce-runner.json
tests/unit/src/__snapshots__/cypress-runner.spec.js.snap
tests/unit/src/__snapshots__/utils.spec.js.snap
tests/unit/src/cypress-runner.spec.js
tests/unit/src/utils.spec.js

* parse `env` from config file (sauce-runner.json) and set in Cypress.run
* refactored and created 2 new methods (with tests) that I intend to reuse across our runners
* made a method `getEnv` that pulls environment variables from sauce-runner.json
* made a method `getArgs` that gets the command line arguments

feat: add cypress env variables from config.yml

---

src/custom-reporter.js

example: https://app.saucelabs.com/tests/53ad5943c45742a3bab8b340f034c36f

Log failure msg in console.log

---

.github/workflows/release.yml
.saucetpl/.sauce/config.yml

+ use non-v version for docker tag

Add cypress version in template

---

src/custom-reporter.js

Fix
```
TypeError: Cannot read property 'frame' of undefined
```

Fix undefined err when output failure msgs

---

src/sauce-reporter.js

Add suite name to a request body for creating a job

Add suite name to a request body for creating a job

---

tests/env-tests/.sauce/config.yml
tests/kitchen-sink-tests/.sauce/config.yml
tests/kitchen-sink-tests/.sauce/config_failing_suites.yml
tests/kitchen-sink-tests/cypress/integration/examples/utilities.spec.js

Cleaning up all config.ymls with regards to latest changes (and any other errors).

Clean up config.yml

---

src/cypress-runner.js

Add support for extra parameters (key, record)

Add support for extra parameters (key, record)

---

.github/workflows/kitchen-sink.yml

Set credentials for saucectl to be able to run the kitchensink pipeline.

Set credentials for saucectl

---

.github/workflows/release.yml

Remove missing reference

---

.github/workflows/release.yml

Generate template with version extracted from `package.json` file

Generate template from package.json value

---

.saucetpl/.sauceignore

add .sauceignore with default content to the .saucetpl folder

add .sauceignore with default content to the .saucetpl folder

---

Dockerfile

Updates label for future uses: `LABEL com.saucelabs.entrypoint=/home/seluser/bin/cypress`

Update label to use entrypoint

---

jest.config.json
package-lock.json
package.json
src/cypress-runner.js
src/sauce-reporter.js
tests/kitchen-sink-tests/cypress/integration/examples/actions.spec.js
tests/kitchen-sink-tests/cypress/integration/examples/example.json
tests/kitchen-sink-tests/cypress/integration/examples/files.spec.js

* also fixed a logging problem (wasn't logging "suites" correctly)
* ignore "cypress/unit" in jest unit tests... these were being run when they shouldn't have

do not show error if cannot find mp4 on sauce cloud

---

.saucetpl/.sauce/config.yml

add platformName for default template

add platformName for default template

---

src/sauce-reporter.js
tests/unit/src/__snapshots__/sauce-reporter.spec.js.snap

Put every assets in the `__assets__` folder flattened.

Fix Screenshot renaming feature

---

src/custom-reporter.js

failed to visit the url -> https://app.saucelabs.com/tests/5ee77feece7a40f49ad3f82e00334da5
failed to do assertion -> https://app.saucelabs.com/tests/196ae0669e864a2bac58441781ab2288

Hide output for expected&actual if both are undefined

---

.saucetpl/.sauce/config.yml
src/sauce-reporter.js
tests/demo-kitchen-sink/.sauce/config.yml
tests/env-tests/.sauce/config.yml
tests/kitchen-sink-tests/.sauce/config.yml
tests/kitchen-sink-tests/.sauce/config_failing_suites.yml
tests/unit/src/__snapshots__/sauce-reporter.spec.js.snap

The suite name will now equal the job name.

Remove support for metadata.name

---

package-lock.json
package.json
src/cypress-runner.js
src/sauce-reporter.js
tests/unit/src/__snapshots__/cypress-runner.spec.js.snap
tests/unit/src/__snapshots__/sauce-reporter.spec.js.snap
tests/unit/src/cypress-runner.spec.js
tests/unit/src/sauce-reporter.spec.js

e.g.
https://app.saucelabs.com/tests/96ff31fb89c04b8c9016b53d91af1e27

[devx-1024] Merge junit files

---

package-lock.json
package.json
src/cypress-runner.js
src/sauce-reporter.js
tests/unit/src/__snapshots__/cypress-runner.spec.js.snap
tests/unit/src/cypress-runner.spec.js

It should escape junit.xml.
e.g. https://app.saucelabs.com/tests/325e02361977432fa301e3e824595d95

[DEVX-1154] escape junit.xml

---

src/sauce-reporter.js

Add default value for failure related fields

[DEVX-1154] Add default value for failure message, type and _CDATA in junit

---

package-lock.json
package.json

verified with example repo.
passed=true suite="Firefox in sauce" url=https://app.saucelabs.com/tests/07fbb527af234b078a6e35198a9009b0
passed=true suite="Chrome using global mode setting" url=https://app.saucelabs.com/tests/8c1fb6d22d8b4a0e96d4a088d19ddde5
passed=true suite="Firefox in docker" url=https://app.saucelabs.com/tests/d3ae5b68b3e549a0922e4cd8635d1810

[DEVX-1159] Bump up cypress version to 8.3.0

---

.github/workflows/integration.yml
.github/workflows/test.yml
package-lock.json
package.json
tests/kitchen-sink-tests/.sauce/config_on_sauce.yml

- Copy bundle to GCS + Test-it against sauce
- Update saucectl to 0.65.0

[DEVX-1189] Test bundle against sauce on PR

---

package-lock.json
package.json

Pre-installation of `cypress-mochawesome-reporter` in cypress runner.
Exemple run with the newly build version of the runner: 
https://app.saucelabs.com/tests/4bc5445739004b4cb4dccef214a4c8d6#0

[DEVX-1322] Pre-install cypress-mochawesome-reporter

---

.github/workflows/integration.yml
.github/workflows/validate.yml
Dockerfile
package-lock.json
package.json
src/cypress-runner.js
tests/unit/src/cypress-runner.spec.js

Create and attach a `sauce-test-report.json` to the job.
Example job:
https://app.saucelabs.com/tests/7b6c7b4a6ca24b15a5f09abf94e2a471

[DEVX-1338] Sauce Test Report JSON

---

.github/workflows/kitchen-sink.yml

[DEVX-1437] Update github checkout action

---

src/cypress-runner.js
tests/env-tests/cypress/e2e/env.cy.js
tests/env-tests/sauce-runner.json

Add `SAUCE_SUITE_NAME` and `SAUCE_ARTIFACTS_DIRECTORY`

[DEVX-1805] Expose additional env vars

---

.github/workflows/integration.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/validate.yml
Dockerfile
package-lock.json
package.json

Update nodejs to 16

---

package-lock.json
package.json
tests/kitchen-sink-tests/cypress/e2e/2-advanced-examples/storage.cy.js

Bump mocha.
Also update kitchen sink tests.

Bump mocha

---

src/cypress-runner.js

The console log would be like
```
Sauce Cypress Runner 10.0.0
Running Cypress 12.3.0
```

[DEVX-2120] Log framework version in console log

---

.github/workflows/test.yml
tests/env-tests/.sauce/config.yml
tests/env-tests/cypress/e2e/env.cy.js
tests/env-tests/sauce-runner.json

See failure in https://github.com/saucelabs/sauce-cypress-runner/actions/runs/4425034034/jobs/7759593002.

Fix pipeline

---

.github/workflows/test.yml

- Limit one pipeline per PR
- Limit to 3 jobs in parallel for the [OS, Browser] matrix testing

Limit concurrency

---

.github/workflows/test.yml

Pipeline Maintenance

---

package-lock.json
package.json

Bump `cypress@12.17.2`
Correct some security issues with `npm audit fix`

Bump cypress@12.17.2 + npm audi fix

---

package-lock.json
package.json

Bump plugin to include changes from https://github.com/saucelabs/sauce-cypress-plugin/pull/63.

deps: bump @saucelabs/cypress-plugin@3.1.1

---

.github/workflows/release.yml

Add description for the Find matching draft tag step.

 chore: Add description for the asset ID retrieval step in the release process

---

.github/workflows/release.yml
.github/workflows/test.yml

ci: bump workflow actions

---

.github/workflows/release.yml
.github/workflows/test.yml

fix(release): Use macos-13 runner

---

tests/post-release/.sauce/config_mac.yml
tests/post-release/.sauce/config_win.yml

fix(release): Use supported version for post-release tests

---

package-lock.json
package.json

deps: Bump Cypress@13.15.2

---

src/cypress-runner.ts

Feature has been deprecated for a minute.
[INT-171]
[INT-171]: https://saucedev.atlassian.net/browse/INT-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Remove support for multi reporter setup
